import { aiTopics, difficulties, platforms } from "../data/defaults";
import type React from "react";
import type { DayEntry } from "../types";
import { Card, Input, Label, Progress, Select, Textarea } from "./ui";

type Props = { day: DayEntry; onChange: (patch: Partial<DayEntry>) => void };
export function DailyForms({ day, onChange }: Props) {
  const dsaPct = Math.round((day.dsa.solved / day.dsa.target) * 100);
  return <div className="grid gap-5 xl:grid-cols-2">
    <Card className="xl:col-span-2"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">DSA</h2><span className="text-sm text-zinc-500">{day.dsa.solved}/{day.dsa.target} questions</span></div><Progress value={dsaPct} className="my-5" /><div className="grid gap-4 md:grid-cols-4"><Field label="Solved"><Input type="number" min={0} max={day.dsa.target} value={day.dsa.solved} onChange={(e) => onChange({ dsa: { ...day.dsa, solved: Number(e.target.value) } })} /></Field><Field label="Difficulty"><Select value={day.dsa.difficulty} onChange={(e) => onChange({ dsa: { ...day.dsa, difficulty: e.target.value as DayEntry["dsa"]["difficulty"] } })}>{difficulties.map((x) => <option key={x}>{x}</option>)}</Select></Field><Field label="Platform"><Select value={day.dsa.platform} onChange={(e) => onChange({ dsa: { ...day.dsa, platform: e.target.value as DayEntry["dsa"]["platform"] } })}>{platforms.map((x) => <option key={x}>{x}</option>)}</Select></Field><Field label="Notes"><Input value={day.dsa.notes} onChange={(e) => onChange({ dsa: { ...day.dsa, notes: e.target.value } })} placeholder="Patterns, misses, wins" /></Field></div></Card>
    <Card><h2 className="mb-4 text-xl font-bold">System Design</h2><Field label="Article name"><Input value={day.system.title} onChange={(e) => onChange({ system: { ...day.system, title: e.target.value } })} /></Field><Field label="URL"><Input value={day.system.url} onChange={(e) => onChange({ system: { ...day.system, url: e.target.value } })} /></Field><label className="mt-2 flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={day.system.read} onChange={(e) => onChange({ system: { ...day.system, read: e.target.checked } })} /> Read</label><Field label="Notes"><Textarea value={day.system.notes} onChange={(e) => onChange({ system: { ...day.system, notes: e.target.value } })} /></Field></Card>
    <Card><h2 className="mb-4 text-xl font-bold">AI Learning</h2><Field label="Topic"><Select value={day.ai.topic} onChange={(e) => onChange({ ai: { ...day.ai, topic: e.target.value } })}>{aiTopics.map((x) => <option key={x}>{x}</option>)}</Select></Field><Field label="Article title"><Input value={day.ai.title} onChange={(e) => onChange({ ai: { ...day.ai, title: e.target.value } })} /></Field><Field label="URL"><Input value={day.ai.url} onChange={(e) => onChange({ ai: { ...day.ai, url: e.target.value } })} /></Field><label className="mt-2 flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={day.ai.completed} onChange={(e) => onChange({ ai: { ...day.ai, completed: e.target.checked } })} /> Completed</label><Field label="Notes"><Textarea value={day.ai.notes} onChange={(e) => onChange({ ai: { ...day.ai, notes: e.target.value } })} /></Field></Card>
    <Card><h2 className="mb-4 text-xl font-bold">HR Preparation</h2><Field label="Question"><Input value={day.hr.question} onChange={(e) => onChange({ hr: { ...day.hr, question: e.target.value } })} /></Field><Field label="Confidence"><Select value={day.hr.confidence} onChange={(e) => onChange({ hr: { ...day.hr, confidence: e.target.value as DayEntry["hr"]["confidence"] } })}>{["Low", "Medium", "High"].map((x) => <option key={x}>{x}</option>)}</Select></Field><label className="mt-2 flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={day.hr.practiced} onChange={(e) => onChange({ hr: { ...day.hr, practiced: e.target.checked } })} /> Answer practiced</label></Card>
    <Card><h2 className="mb-4 text-xl font-bold">Notes</h2><Textarea value={day.notes} onChange={(e) => onChange({ notes: e.target.value })} placeholder="Daily reflection, blockers, topics to revisit" /></Card>
  </div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="mb-3"><Label>{label}</Label>{children}</div>; }
